### ISSUE TITLE
Simple WebAPI clients get booted out of Consul due to lack of health check

### ISSUE THREAD

**Issue by PhilipDaniels** [lvermeulen/Nanophone#10]
This is more to ask for guidance than a bug report. I made a very simple WebAPI service and registered it using Nanophone, which succeeded, but Consul booted it out of the cluster, I think because it did not implement any sort of health check.

It's probably a good idea to have a health check of course, but I was wondering if you had any thoughts on this? Microphone seems to register a default health check. This is all new to me so I don't know what best practice is yet, but the "getting started" story needs to be as simple as possible.

Here is the consul log FWIW

```
2016/07/20 11:19:31 [INFO] agent: Synced service 'consul'
```

==> Failed to check for updates: Get https://checkpoint-api.hashicorp.com/v1/check/consul?arch=amd64&os=windows&signature=&version=0.6.4: dial tcp 54.221.230.67:443: connectex: No connection could be made because the target machine actively refused it.
    2016/07/20 11:21:02 [DEBUG] agent: Service 'consul' in sync
    2016/07/20 11:22:25 [WARN] Service tag "version-1.0" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2016/07/20 11:22:25 [DEBUG] agent: Service 'consul' in sync
    2016/07/20 11:22:25 [INFO] agent: Synced service 'case-id_localhost_9000'
    2016/07/20 11:22:25 [DEBUG] agent: Check 'service:case-id_localhost_9000' in sync
    2016/07/20 11:22:25 [DEBUG] http: Request PUT /v1/agent/service/register (2ms) from=127.0.0.1:56229
    2016/07/20 11:22:25 [DEBUG] agent: Service 'consul' in sync
    2016/07/20 11:22:25 [DEBUG] agent: Service 'case-id_localhost_9000' in sync
    2016/07/20 11:22:25 [DEBUG] agent: Check 'service:case-id_localhost_9000' in sync
    2016/07/20 11:22:25 [DEBUG] agent: Service 'consul' in sync
    2016/07/20 11:22:25 [DEBUG] agent: Service 'case-id_localhost_9000' in sync
    2016/07/20 11:22:25 [DEBUG] agent: Check 'service:case-id_localhost_9000' in sync
    2016/07/20 11:22:25 [DEBUG] agent: pausing 273.409331ms before first HTTP request of http://localhost:9000//status
    2016/07/20 11:22:27 [WARN] agent: http request failed 'http://localhost:9000//status': Get http://localhost:9000//status: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    2016/07/20 11:22:28 [WARN] agent: check 'service:case-id_localhost_9000' is now critical
    2016/07/20 11:22:29 [WARN] agent: check 'service:case-id_localhost_9000' is now critical
    2016/07/20 11:22:30 [WARN] agent: check 'service:case-id_localhost_9000' is now critical
    2016/07/20 11:22:31 [WARN] agent: check 'service:case-id_localhost_9000' is now critical
    2016/07/20 11:22:32 [WARN] agent: check 'service:case-id_localhost_9000' is now critical
    2016/07/20 11:22:33 [WARN] agent: check 'service:case-id_localhost_9000' is now critical
    2016/07/20 11:22:34 [WARN] agent: check 'service:case-id_localhost_9000' is now critical
    2016/07/20 11:22:35 [DEBUG] http: Request GET /v1/health/state/critical (0) from=127.0.0.1:56229
    2016/07/20 11:22:35 [DEBUG] agent: Service 'consul' in sync
    2016/07/20 11:22:35 [INFO] agent: Deregistered service 'case-id_localhost_9000'
    2016/07/20 11:22:35 [INFO] agent: Deregistered check 'service:case-id_localhost_9000'
    2016/07/20 11:22:35 [DEBUG] http: Request PUT /v1/agent/service/deregister/case-id_localhost_9000 (999.2µs) from=127.0.0.1:56229
    2016/07/20 11:22:35 [DEBUG] agent: Service 'consul' in sync
    2016/07/20 11:22:35 [DEBUG] agent: Service 'consul' in sync
    2016/07/20 11:22:37 [DEBUG] agent: Service 'consul' in sync
    2016/07/20 11:22:40 [DEBUG] http: Request GET /v1/health/state/critical (0) from=127.0.0.1:56229

**Comment by lvermeulen** [comment]
@PhilipDaniels A health check is definitely registered - maybe Consul is kicking it out before it came up? Try ignoring critical services in your ConsulRegistryHostConfiguration and see what happens. Did you start with your own project, or with the sample projects in the Nanophone repo? If the former, I suggest you clone the repo and take a look at the samples.
