### ISSUE TITLE
Add aspnetcore configuration provider

### ISSUE THREAD

**Issue by lvermeulen** [lvermeulen/Nanophone#18]
From [feature request](https://github.com/PlayFab/consuldotnet/issues/65) at [consuldotnet](https://github.com/PlayFab/consuldotnet)
- [x] Add configuration provider using Nanophone keyvalues middleware
- [x] Add configuration provider tests

**Comment by johnmckinzie** [comment]
Myself or someone else from my team can probably contribute if you would like some help. For our purposes, we only need the KV functionality and not the service discovery (we are handling through a different mechanism), so I'm hoping they aren't coupled (seemed like they were in Microphone, so I went with Consul.NET).

**Comment by lvermeulen** [comment]
Let me see how far I get this week, I'll keep you posted.

**Comment by johnmckinzie** [comment]
Sounds good. I seems pretty doable just based on what I did this morning.

**Comment by lvermeulen** [comment]
@johnmckinzie Code and tests are ready in branch [configurationprovider](https://github.com/lvermeulen/Nanophone/tree/configurationprovider), will release a package in one or two days.

**Comment by johnmckinzie** [comment]
Impressive speed @lvermeulen. I'll take a look tomorrow.

**Comment by lvermeulen** [comment]
@johnmckinzie I'm having an issue with Appveyor right now, as soon as that's resolved there will be a release.

**Comment by johnmckinzie** [comment]
That's fine @lvermeulen. End of the week got away from me, so I didn't get to pull in the source code. I'll shoot for Monday and provide any feedback.

**Comment by lvermeulen** [comment]
Release [1.6.0-alpha](https://github.com/lvermeulen/Nanophone/releases/tag/1.6.0-alpha)

**Comment by lvermeulen** [comment]
@johnmckinzie Available with nuget as 1.6.0-alpha

**Comment by johnmckinzie** [comment]
@lvermeulen I'm playing the the package and I have a question. In your tests, I see that you are testing the configuration via `GetSettings()` on the `WebHostBuilder` class.. However, I'm using it in my service's `Startup.cs` using `GetValue()` on the configuration object returned by the configuration builder. Below is a snippet:

```
            // Set up configuration sources.
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json")
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", true)
                .AddEnvironmentVariables()
                .AddNanophoneKeyValues(() => new ConsulRegistryHost());

            Configuration = builder.Build();

            Console.WriteLine("getting hello...");
            var bar = Configuration.GetValue<string>("test:hello");
            Console.WriteLine($"hello: {bar}");
```

I'm running a local Docker Consul instance based on the instructions here: https://hub.docker.com/r/progrium/consul/

I manually added the "hello" key via the Consul UI. However, when I run my service, I only get an empty string back via the `GetValue()` call. 

Am I using it incorrectly?

![screenshot from 2016-08-15 12-22-17](https://cloud.githubusercontent.com/assets/2511456/17671087/14ec8730-62e3-11e6-9a49-38d34ab73684.png)

**Comment by lvermeulen** [comment]
@johnmckinzie While trying to reproduce I actually hit a pretty bad [bug in my code](https://github.com/lvermeulen/Nanophone/issues/21). It's fixed in [1.6.1-alpha](https://github.com/lvermeulen/Nanophone/releases/tag/1.6.1-alpha), so you might want to update.

As far as using incorrectly - I see you're instantiating ConsulRegistryHost without parameters, which implies that it's running on localhost:8500. If that's not where it's running, then you can instantiate it with a ConsulRegistryHostConfiguration which allows you to specify host and port.

**Comment by lvermeulen** [comment]
@johnmckinzie One more thing - remember that your Startup is called after ConfigureServices and Configure, so you can't use your configuration inside those two methods. The following code will work:

```
    public Startup(IHostingEnvironment env)
    {
        var builder = new ConfigurationBuilder()
            .SetBasePath(env.ContentRootPath)
            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
            .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
            .AddNanophoneKeyValues(() => new ConsulRegistryHost());

        builder.AddEnvironmentVariables();
        Configuration = builder.Build();
        var value = Configuration.GetValue<string>("hello");
    }
```

**Comment by johnmckinzie** [comment]
@lvermeulen The snipped I provided above was in my `Startup`. I'm a little confused about your following statement:

> remember that your Startup is called after ConfigureServices and Configure, so you can't use your configuration inside those two methods

The `Startup` function is the constructor. That is called before `ConfigureServices` and `Configure` according to the documentation: https://docs.asp.net/en/latest/fundamentals/startup.html.

Here is my entire `Startup`:

```
        public Startup(IHostingEnvironment env)
        {
            // Set up configuration sources.
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json")
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", true)
                .AddNanophoneKeyValues(() => new ConsulRegistryHost())
                .AddEnvironmentVariables();

            Configuration = builder.Build();

            Console.WriteLine("getting hello...");
            var world = Configuration.GetValue<string>("test:hello");
            Console.WriteLine($"hello: {world}");
        }
```

I'm still just receiving an empty string, even those Consul is running on port 8500 and I've created the `hello` key with a value of `world`.

Curl output:

```
➜  NerfBlastersService git:(nanophone) ✗ curl -v 'http://localhost:8500/v1/kv/?recurse'
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET /v1/kv/?recurse HTTP/1.1
> Host: localhost:8500
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Consul-Index: 8
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 0
< Date: Tue, 16 Aug 2016 14:23:43 GMT
< Content-Length: 92
< 
* Connection #0 to host localhost left intact
[{"CreateIndex":8,"ModifyIndex":8,"LockIndex":0,"Key":"hello","Flags":0,"Value":"d29ybGQ="}]%          
```

**Comment by lvermeulen** [comment]
@johnmckinzie You're right to be a little confused, because I was utterly confused - my mind was thinking of some adventures with dependency injection instead of configuration. :-S

From what I see in your curl output, the key "hello" exists with the value "world" (base64-encoded value "d29ybGQ"). However in your code you're fetching the value of key "test:hello" and from your screenshot I -think- you have a folder "test", perhaps with the key "hello" in it? If you want to get key "hello" from folder "test", you would use key "test/hello" instead of "test:hello", so a forward slash instead of a colon.

This is my curl output with both keys "hello" and "test/hello", you can see both have values "world":

```
$ curl -v http://localhost:8500/v1/kv/?recurse
* About to connect() to localhost port 8500 (#0)
*   Trying 127.0.0.1...
* connected
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET /v1/kv/?recurse HTTP/1.1
> User-Agent: curl/7.28.1
> Host: localhost:8500
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Consul-Index: 34
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 0
< Date: Tue, 16 Aug 2016 17:11:03 GMT
< Content-Length: 191
<
[{"LockIndex":0,"Key":"hello","Flags":0,"Value":"d29ybGQ=","CreateIndex":6,"ModifyIndex":23},{"LockIndex":0,"Key":"test/hello","Flags":0,"Value":"d29ybGQ=","CreateIndex":34,"ModifyIndex":34}]* Connection #0 to host localhost left intact
* Closing connection #0
```

**Comment by johnmckinzie** [comment]
@lvermeulen It's working now. I was experimenting with different paths b/c I had previously seen some weirdness. Obviously fixing the path, along with your 1.6.1 update, did the trick. If you want to put on the README some desired donations, I might be able to swing a little something

**Comment by lvermeulen** [comment]
@johnmckinzie Glad it works! And if you can swing something, swing it their way: [http://www.curethekids.org/](http://www.curethekids.org/).

**Comment by johnmckinzie** [comment]
Done. Thanks again! I'll create issues if I run into anything.

**Comment by lvermeulen** [comment]
@johnmckinzie You might want to update to [1.6.2-alpha](https://github.com/lvermeulen/Nanophone/releases/tag/1.6.2-alpha), I fixed a race-condition. Beware that it's now using Consul 0.7.0 instead of 0.6.4

**Comment by johnmckinzie** [comment]
Appreciated the heads up. I'll take a look it next week.
