### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by Mikular** [lvermeulen/Nanophone#2]
Hi there,

Now that .NET Core RTM has been released, are there any plans to update this project to support it? Thanks.

**Comment by lvermeulen** [comment]
Hi Dan,

Yes, it's in the works, specifically in branch [feature/vnext](https://github.com/lvermeulen/Nanophone/tree/feature/vnext). The dependency on [Consul.NET](https://github.com/PlayFab/consuldotnet) is in alpha, and is itself waiting on a Newtonsoft.Json fix.
To be fair, the major issue is me trying to wrap my mind around .NET Core.

[Issue](https://github.com/lvermeulen/Nanophone/issues/3) created.
