### ISSUE TITLE
Tags are always null

### ISSUE THREAD

**Issue by sinegovsky-ivan** [lvermeulen/Nanophone#23]
Hello!

Thank you for your work!

I have a small issue:

Then i request services via FindServiceInstancesAsync, property tag of the RegistryInformation is always null.

How i can fill this property ?

**Comment by lvermeulen** [comment]
Thanks for reporting this issue! I pushed a fix and will update the NuGet packages later.

**Comment by sinegovsky-ivan** [comment]
Thank you!
