### ISSUE TITLE
Support .NET Core RTM

### ISSUE THREAD

**Issue by lvermeulen** [lvermeulen/Nanophone#3]
Branch [feature/vnext](https://github.com/lvermeulen/Nanophone/tree/feature/vnext)
- [x] Nanophone.Core
- [x] Nanophone.Core.Tests
- [x] Nanophone.RegistryHost.ConsulRegistry
- [x] Nanophone.RegistryHost.ConsulRegistry.Tests
- [x] Nanophone.RegistryTenant.Nancy
- [x] Nanophone.RegistryTenant.WebApi
- [x] Samples\SampleClient.net451
- [x] Samples\SampleService.Nancy.net451
- [x] Samples\SampleService.WebApi.SelfHost.net451
- [x] Add netcore samples
- [x] Use compatible Consul package
- [x] Use compatible Nancy package
- [x] Build packages
- [x] Update appveyor.yml
- [x] Merge to master

**Comment by lvermeulen** [comment]
@Dan-McElroy some more visibility into progress

**Comment by Mikular** [comment]
@lvermeulen Thanks for letting me know about this. Looks like it's nearly there!

**Comment by lvermeulen** [comment]
@Dan-McElroy You're welcome! It's been quite the .NET Core learning experience. :-)

**Comment by lvermeulen** [comment]
Available as [Nanophone.*.1.2.0-alpha](https://www.nuget.org/packages/Nanophone.Core/1.2.0-alpha)

**Comment by Mikular** [comment]
Thanks for this!
